### ISSUE TITLE
slice::compare() does not work as expected.

### ISSUE THREAD

**Issue by banks** [rescrv/e#10]
I re-used the slice.h/cc in a project as it was a convenient bit of code to re-use without pulling in larger dependencies.

While reading it I noticed that the compare method seems to be either trivially wrong or at least not what i would have expected...

The implementation is:

```
inline int
slice :: compare(const slice& rhs) const
{
    if (m_sz < rhs.m_sz)
    {
        return -1;
    }
    else if (m_sz > rhs.m_sz)
    {
        return 1;
    }
    else
    {
        return memcmp(m_data, rhs.m_data, m_sz);
    }
}
```

So `compare()` sorts slices based on length _alone_, and only if they happen to be same length does it give (expected) lexicographical comparison.

As a result `slice("z")` sorts _before_ `slice("aaa")`.

Is this intentional? Seems a large oversight if that class is ever used anywhere if not. If it is intentional, what is the rationale for that behaviour. I'm not sure I see how it would ever be useful...

**Comment by banks** [comment]
Of course I'm happy to give a (trivial) pull request to fix it as I have in my own version, but it seemed so obvious I wanted to check if it was actually my misunderstanding.

**Comment by rescrv** [comment]
The rational was to give a fast comparator for use in STL set structures.  I don't use it as a lexicographical compare.  I'm happy to change it, as no persistent structures I've written rely upon this comparator.

**Comment by rescrv** [comment]
Looking at some of the code we have in use, it turns out we do indeed use the comparator in some cases, so I need to rely upon the "fast, not lexicographic" feature.  I've documented this behavior.

**Comment by HyphensPeciwse33** [comment]
Duplicate of #12 #1
